---
- name: Create loopback payload from template
  hosts: 172.16.1.25
  connection: local

  tasks:
    - name: Create template
      with_items: "{{local_loopback}}"  # these are stored in a variable called "item" 
      template: src="files/ietf_inteface.j2" dest="./output.json"